import type { Metadata } from "next";
import { Sora, Poppins } from "next/font/google";
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false
import "./globals.css";

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
})

const poppins = Poppins(
  {
    weight: '400',
    variable: "--font-poppins",
    subsets: ["latin"],
  }
);


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${sora.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
